### PR TITLE
Add PPL Electric Init

### PR DESCRIPTION
**Pull request by JVital2013**
More info available at https://github.com/merbanan/rtl_433/issues/2531#issuecomment-1722479312

### CODE REVIEW

**Comment by rct** [comment]
I'm trying to work out the CRC init for PSEGLINY.  What needs to be done to feed captured strings into reveng?

From @JVital2013 log_landis.csv, I have data like


```
{320}2a55002330fffffffffffffef1073a0500c4000c86d8a40bf1073a050100082e02082f7e90af4004
{320}2a55002330fffffffffffffef1073a0500cc000c39a9a40bf1073a050100082e0202fd7e90170104
{320}2a55002330fffffffffffffef1073a0500ce000c4202a40bf1073a050100092e020e797e90373204
{320}2a55002330fffffffffffffef1073a0500d0000c853aa40bf1073a050100082e020b317e90626304
{320}2a55002330fffffffffffffef1073a0500d6000c8c20a40bf1073a050100082e0212d97e90db9d04
{320}2a55002330fffffffffffffef1073a0500e6000c6cfaa40bf1073a050100082e02082f7e90062704
```

If I feed them in unmodified, I get a init 0x5ea2 where I should get 0x47f7

```
$ ./reveng -w 16 -s 2a55002330fffffffffffffef1073a0500e6000c6cfaa40bf1073a050100082e02082f7e90062704 2a55002330fffffffffffffef1073a0500d6000c8c20a40bf1073a050100082e0212d97e90db9d04 2a55002330fffffffffffffef1073a0500d0000c853aa40bf1073a050100082e020b317e90626304 2a55002330fffffffffffffef1073a0500c4000c86d8a40bf1073a050100082e02082f7e90af4004 2a55002330fffffffffffffef1073a05001a000c5e47a40bf1073a050100082e0213f17e902bc704
width=16  poly=0x1021  init=0x5ea2  refin=false  refout=false  xorout=0x0000  check=0x47dc  residue=0x0000  name=(none)
```

If I take off the trailing 0x04, and the 2 bytes before that that are the CRC, or just the trailing 04, I get no models found

```
$ ./reveng -w 16 -s 00ff2a55002330fffffffffffffef1073a0500e6000c6cfaa40bf1073a050100082e02082f7e90 00ff2a55002330fffffffffffffef1073a0500d6000c8c20a40bf1073a050100082e0212d97e90 2a55002330fffffffffffffef1073a0500d0000c853aa40bf1073a050100082e020b317e90 2a55002330fffffffffffffef1073a0500ce000c4202a40bf1073a050100092e020e797e90 2a55002330fffffffffffffef1073a0500cc000c39a9a40bf1073a050100082e0202fd7e90
./reveng: no models found
```

**Comment by krvmk** [comment]
You have to strip off the header 2a550023. The last byte is the number of characters following - 0x23 which is 35 in decimal. Count 35 characters after that and end there. In your case above, that would truncate the trailing 04:
```
reveng -w 16 -s 30fffffffffffffef1073a0500c4000c86d8a40bf1073a050100082e02082f7e90af40 30fffffffffffffef1073a0500cc000c39a9a40bf1073a050100082e0202fd7e901701 30fffffffffffffef1073a0500ce000c4202a40bf1073a050100092e020e797e903732 30fffffffffffffef1073a0500d0000c853aa40bf1073a050100082e020b317e906263 30fffffffffffffef1073a0500d6000c8c20a40bf1073a050100082e0212d97e90db9d 30fffffffffffffef1073a0500e6000c6cfaa40bf1073a050100082e02082f7e900627
width=16  poly=0x1021  init=0x47f7  refin=false  refout=false  xorout=0x0000  check=0x5524  residue=0x0000  name=(none)
```

**Comment by rct** [comment]
Thanks, so it looks like the init value for PSEG Long Island (PSEGLINY) is `0x22c6`

`width=16  poly=0x1021  init=0x22c6  refin=false  refout=false  xorout=0x0000  check=0xdbc2  residue=0x0000  name=(none)`

Here's how I got that:

```
$ perl -lanF, -e 'print $F[2]'  log_landis.csv  | grep 2a550023   | egrep 04$ | perl -pe 's/.320.2a550023//;s/04$//'  | tail -15
30fffffffffffffef144cfa400a200bfac10a40bf144cfa401000d3c030aeb7e904094
30fffffffffffffef144cfa400a800bfad18a40bf144cfa401000d3c0313f17e90fb5e
30fffffffffffffef144de91000a00bfad6ca40bf144de9101000ca2030cd57e908c38
30fffffffffffffef144aefb00b000bfae03a40bf144aefb01000da20210a97e902bc7
30fffffffffffffef05acac0007e00131874a40bf05acac001000ca20314377e90ebc2
30fffffffffffffef144aefb00ba00bfaf33a40bf144aefb01000da20211c17e90cc9a
30fffffffffffffef144de91008800bfb269a40bf144de9101000ca20312077e90fce5
30fffffffffffffef144de9100cc00bfb48da40bf144de9101000ca203147d7e908fc7
30fffffffffffffef144cfa4001400bfb5a6a40bf144cfa401000c3c0305737e90b300
30fffffffffffffef144cfa4002000bfb649a40bf144cfa401000c3c0316227e003874
30fffffffffffffef144cd4e00f600bfbb74a40bf144cd4e01000fa20308757e9017a5
30fffffffffffffef144cfa400c800bfbe1aa40bf144cfa401000c3c0304157e9071c1
30fffffffffffffef144de91002c00bfbfd2a40bf144de9101000ca20312937e907250
30fffffffffffffef144cd4e003e00bfc114a40bf144cd4e010010a203068b7e90acfe
30fffffffffffffef03c4cb700ba00bfc1cfa40bf03c4cb701000ca20305ff7e9060a5
```

And the reveng output
```
$ ./reveng -w 16 -s 30fffffffffffffef144cfa400a200bfac10a40bf144cfa401000d3c030aeb7e904094 30fffffffffffffef144cfa400a800bfad18a40bf144cfa401000d3c0313f17e90fb5e 30fffffffffffffef144de91000a00bfad6ca40bf144de9101000ca2030cd57e908c38 30fffffffffffffef144aefb00b000bfae03a40bf144aefb01000da20210a97e902bc7 30fffffffffffffef05acac0007e00131874a40bf05acac001000ca20314377e90ebc2 30fffffffffffffef144aefb00ba00bfaf33a40bf144aefb01000da20211c17e90cc9a 30fffffffffffffef144de91008800bfb269a40bf144de9101000ca20312077e90fce5 30fffffffffffffef144de9100cc00bfb48da40bf144de9101000ca203147d7e908fc7 30fffffffffffffef144cfa4001400bfb5a6a40bf144cfa401000c3c0305737e90b300 30fffffffffffffef144cfa4002000bfb649a40bf144cfa401000c3c0316227e003874 30fffffffffffffef144cd4e00f600bfbb74a40bf144cd4e01000fa20308757e9017a5 30fffffffffffffef144cfa400c800bfbe1aa40bf144cfa401000c3c0304157e9071c1 30fffffffffffffef144de91002c00bfbfd2a40bf144de9101000ca20312937e907250 30fffffffffffffef144cd4e003e00bfc114a40bf144cd4e010010a203068b7e90acfe 30fffffffffffffef03c4cb700ba00bfc1cfa40bf03c4cb701000ca20305ff7e9060a5
width=16  poly=0x1021  init=0x22c6  refin=false  refout=false  xorout=0x0000  check=0xdbc2  residue=0x0000  name=(none)
```

**Review by krvmk — APPROVED** [review]

**Comment by rct** [comment]
@krvmk - what do you want me to do with the init value 0x22c6 for PSEGLINY? 

`{0x22c6, "Long Island, NY", "PSEG Long Island"}};`

I can open another PR if you want it for tracking, I see you approved this PR but didn't merge yet.

**Comment by krvmk** [comment]
> @krvmk - what do you want me to do with the init value 0x22c6 for PSEGLINY?
> 
> `{0x22c6, "Long Island, NY", "PSEG Long Island"}};`
> 
> I can open another PR if you want it for tracking, I see you approved this PR but didn't merge yet.

I have another update to do as well, so please post another PR.

**Pull request closed without merging**
